service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

	
plugins:
  - serverless-plugin-typescript
  - serverless-offline


functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'
